### ISSUE TITLE
Deploy WAR to Apache Tomcat: Content Encoding Error

### ISSUE THREAD

**Issue by asmbit** [groovyzk/grailszk#20]
I'm not able to run the [grailszk-example](https://github.com/maiconandsilva/grailszk-example) within a Tomcat Application Container as described in https://docs.grails.org/4.0.0/guide/deployment.html#deploymentContainer.

**Comment by maiconandsilva** [comment]
Do you have any Stacktrace log to show? 

Any chance it might be related to this issue? (https://github.com/grails/grails-core/issues/12829#issue-1526082178)

**Comment by asmbit** [comment]
"java -jar grailszk-example-0.1.war" works fine. But when i copy the same war to a Tomcat container (9.0.71) i get attached screen. Sorry. No Stracktrace log.

- Grails 4.1.2
- clean Tomcat 9.0.71 or Tomcat 8.5 installation


![2023-02-20 14_31_42-Seiten-Ladefehler – Mozilla Firefox](https://user-images.githubusercontent.com/44233176/220122981-8038b8ef-89b5-4eca-9f80-7ec26ea11fb0.png)
[logs.zip](https://github.com/groovyzk/grailszk/files/10784921/logs.zip)

**Comment by maiconandsilva** [comment]
Ok. I'll take a look at it.

**Comment by asmbit** [comment]
Hi Maicon, can i support you in some manner to resolve the issue. Thanks, Andreas

**Comment by maiconandsilva** [comment]
Hi, Andreas. Sorry it's taking too much time but I've been busy as of late. I'll solve this pressing issue as soon as I can. Although I can't give any particular date.

Also, you can try to solve this issue and make a pull request. Let me know if you are interested.


In the meantime, is it possible for you to deploy your app using the embedded tomcat? (`java -jar myapp.war`)

**Comment by asmbit** [comment]
Hi Maicon, there is no pressure on time. I can wait. Till now i have no experience in grails plugin development, but if i find time i will give a try.  Thanks for your feedback.

**Comment by maiconandsilva** [comment]
@asmbit, can you test your app with the lastest version?

**Comment by asmbit** [comment]
Hi @maiconandsilva, [grailszk-example](https://github.com/maiconandsilva/grailszk-example) now works. But my application has same problem as before. I will investigate more and let you know. Thanks a lot!

**Comment by maiconandsilva** [comment]
@asmbit

Have you changed the version in your application?
How do you call the zul view in your application?

You can create an example in which I can reproduce this error to fix it.

**Comment by asmbit** [comment]
@maiconandsilva 

Yes, i changed version to 3.2.3.
I call the zul view by a controller invoking "forward". See example below:

```
package file.upload
class Test2Controller {
	def index() {
		forward uri: '/index.zul'
	}
}
```

With "bootRun" everything works fine. When deploying the war in Tomcat, i get the error as described before.


Have a nice day and thanks a lot!

**Comment by asmbit** [comment]
Hi @maiconandsilva, i found a better solution instead of forward:

```
package file.upload
class Test2Controller {
	
	def index() {
		response.outputStream << z.wrapper(url: '/index.zul')
	}
}

```

For me the issue is solved. Thank you for your great readiness.

**Comment by maiconandsilva** [comment]
Oh, Thank you. I'm going to check out the issue with using `forward`

**Comment by maiconandsilva** [comment]
The problem is that ZK's `web-fragment.xml` is being loaded with the deployed war, meaning ZK's configured `DHtmlLayoutServlet` is being run last. The problem is that by default `compress` is set to true which returns a gzipped response causing encoding error. For now, there are the known workarounds below:

Adding the following solves the issue if your _ZK version is 8.6.0 or later_:

```groovy
configurations.all {
    exclude group: "org.zkoss.zk", module: "zkwebfragment"
}
```

For prior versions:

 - Create a file named `web.xml` in the `WEB-INF` directory of your project if it does not already exist.
 - Add the `metadata-complete="true"` attribute to the <web-app> element in the `web.xml` file.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="3.0" xmlns="http://java.sun.com/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
         metadata-complete="true">

</web-app>
```

See updated grailszk-example.

PS: There are other methods to prevent the `web-fragment.xml` from being loaded.

**Comment by asmbit** [comment]
Great job! Thank you :)
